### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by lvegerano** [iamchathu/changeset-conventional-commits#12]
I'm not sure if I'm doing this correctly. I'm using `npm` running `npx changeset-conventional` does nothing really.

**Comment by iamchathu** [comment]
Please use `npx changeset-conventional-commits`. I tested it working. Will update the Readme soon

**Comment by macojaune** [comment]
Same for me, all I get is : ```
 From [github repo url]
 * branch            main       -> FETCH_HEAD
```
in my terminal
