### ISSUE TITLE
Duplicate Generation of Changesets

### ISSUE THREAD

**Issue by mblackrittr** [iamchathu/changeset-conventional-commits#26]
I'm not sure if this sneaked in by some updated external package(s), or if it really stayed undetected for so long, but it generates the same Changesets over and over again, because its duplicate detection fails on the still trailing line break `\n` it gets from `git`.

Imagine this example data it holds while duplicate checking.

`const changesets = ...`:
```js
// Data from Commits
[
  {
    releases: [ [Object], [Object] ],
    summary: 'chore(root): add two test packages\n',
    packagesChanged: [ [Object], [Object] ]
  }
]
````

`const currentChangesets = ...`:
```js
// Data from Changesets
[
  {
    releases: [ [Object], [Object] ],
    summary: 'chore(root): add two test packages',
    packagesChanged: [ [Object], [Object] ]
  }
]
````

The issue is here:
https://github.com/iamchathu/changeset-conventional-commits/blob/a4d324693eca549b0d016a162442eef49477ec75/src/utils/index.ts#L165

An added `.replace(/\n$/, '')` fixes it:
```ts
return a.summary.replace(/\n$/, '') === b.summary && JSON.stringify(a.releases) == JSON.stringify(b.releases);
````

MR/PR coming - one of at least a few, haha! 😻

Beside other ideas, I think there should likely be some `--verbose` flag option, that would be great.

E.g. while running first tests, I'd already a tag on the latest commit, so there were just no commits for it to process, but there was no feedback, so I put a bunch of `console.log()` into `node_modules/changeset-conventional-commits/bin/index.js` and saw that they all gave empty arrays, which made finding the issue (me and myself) quite easy! 🥳🎉

It also simplified resolving this issue of duplicate generation.

So, yeah, there'll be more MRs/PRs - because for me, Conventional Commits/Changelogs missing was a total deal breaker on Changesets at first, so this is a great addition to Changesets we should push forward - ***HARD!*** 😹💦

**Comment by iamchathu** [comment]
Thanks for looking deep in to this and suggestion. You contributions will make this helper handle the edge cases also.

**Comment by mblackrittr** [comment]
Super thanks, @iamchathu!

You've any preference on a specific logger? Else I would probably just take [TSLog](https://tslog.js.org/) ([Git](https://github.com/fullstack-build/tslog)) and [meow](https://github.com/sindresorhus/meow) in some `verbosity`. 😻

**Comment by mblackrittr** [comment]
Oh, haha, Changesets already brings its own [@changesets/logger](https://github.com/changesets/changesets/tree/main/packages/logger), so I'll of course just use this, even if it seems ["slightly" aged by now](https://github.com/changesets/changesets/blob/main/packages/logger/src/index.ts), but it'll do the job.

Guess we should give some love and tune `@changesets/logger` itself later on, yeah! 😻

**Comment by iamchathu** [comment]
It's merged and released in latest version v0.2.5. Thank you very much for the contribution!

**Comment by mblackrittr** [comment]
Ah yeah, super thanks - next's also ready now after some tweaking, and as it's a bigger change, let me know if you've any concerns.

Also with this commit I noticed it could've just used `trimEnd()` instead of `replace()`, but then - could also see consistency in using `replace()` instead of different specifics, maybe. haha

**Comment by iamchathu** [comment]
@mblackrittr Now I think trimEnd is also readable. But now we have fix the issue. That's the outcome we archived.
